### PR TITLE
Attempt Django 2.0 support

### PR DESCRIPTION
**Pull request by rtpg**
This branch includes a couple changes that should let people use this library in Django 2.0 without too many issues

### CODE REVIEW

**Comment by igorkurochka** [comment]
hi! @rtpg thanks for the efforts! are you in touch with the maintainers? 
any chance the PR will be merged soon?

**Comment by rtpg** [comment]
@igorkurochka I've sent an email way back about this offering to take over maintenance of this library, but didn't hear back from them. Will try again today.

**Comment by igorkurochka** [comment]
@rtpg I'm going to use the package directly from your repo@branch for now
thanks again!

**Comment by igorkurochka** [comment]
@rtpg I've found one more onresolved issue, floppyforms/gis/widgets.py, line 87 uses `gdal.OGRException` which was removed after merged with GDALException in Django 1.8 https://code.djangoproject.com/ticket/28559 

would be great if you resolve this in your fork. thanks

**Comment by rtpg** [comment]
OK we have been running this branch for a while in production and I am happy with the results. GeoDjango support is broken in 2.0 still until we fix #205, so we can't say that 2.0 support is complete just yet, but this fixes up a good amount of issues.

**Pull request merged**
